Facilitate dapp login with multicall dao accounts
near-multicall/ui pull request #156
Opened 2022-09-02 21:42 UTC by Rin-Akaia-eth

2022-09-05 21:04 UTC, mohamedalichelbi approved these changes

2022-09-05 21:34 UTC, lennczar requested changes
Just some minor code style issues

2022-09-05 21:34 UTC, lennczar commented on src/components/sidebar/dialogs.scss
> +        gap: 16px;
please use `size.$gap`, if necessary with a factor.

2022-09-05 21:34 UTC, lennczar commented on src/components/tooltip/index.js
> +        title={<h1 style={{ fontSize: "12px" }}>{title}</h1>}
please move styles into the corresponding .scss file and use `size.$text` / `size.$large-text` or similar dynamic sized instead of hard coding it.

2022-09-05 21:34 UTC, lennczar commented on src/components/sidebar/dialogs.js
> +            <ul style={{ listStyleType: "decimal", padding: "0 20px" }}>
please move styles to .scss file

2022-09-05 21:34 UTC, lennczar commented on src/components/sidebar/dialogs.js
> +                                <InfoOutlined sx={{ pl: 1 }} />
please move styles to .scss file. I think a larger font-size would be nice here.

2022-09-08 16:20 UTC, lennczar approved these changes

2022-09-08 16:27 UTC, merged