Feature/token balances dao
near-multicall/ui pull request #158
Opened 2022-09-05 21:14 UTC by yukamend

still not fully finished, but functionality is there

2022-09-06 12:39 UTC, mohamedalichelbi commented
TODOs:
- [ ] Display token Icons left to Token symbols and in circular form, similar to NEAR wallet.
- [ ] Move Tokens whitelist back next to Admins list.
- [ ] Load tokens when tabs are switched to view funds.
- [ ] Show the non-selected tabs in a clearer way (now they just blend in with the background).

2022-09-17 01:30 UTC, lennczar requested changes
Please merge the two `components` directories

2022-09-17 01:30 UTC, lennczar commented on src/near-config.js
> -                helperUrl: "https://helper.mainnet.near.org",
whats this?

2022-09-17 01:30 UTC, lennczar commented on src/shared/ui/components/table/index.tsx
> +const StyledTableContainer = styled(TableContainer)({
Please move all css to a seperate file

2022-09-17 01:30 UTC, lennczar commented on src/shared/ui/components/table/index.tsx
> +                                                        fill: (theme) =>
for css like this lets find a different solutions, we are not even using an mui theme

2022-09-17 01:30 UTC, lennczar commented on src/shared/ui/components/tabs/index.tsx
> +            <Box>
unnecessary `<Box>`. Also please use divs. To my understanding the only benefit of Box is that is works with sx props. But we dont have/want CSS in JS.

2022-09-17 01:30 UTC, lennczar commented on src/shared/ui/components/token-label/token-label.scss
> +    gap: 14px;
please do not use hard coded values.

2022-09-17 02:03 UTC, Rin-Akaia-eth commented on src/near-config.js
> -                helperUrl: "https://helper.mainnet.near.org",
@yukamend

2022-09-18 16:29 UTC, Rin-Akaia-eth commented on src/near-config.js
> -                helperUrl: "https://helper.mainnet.near.org",
/cast @mohamedalichelbi

2022-09-21 20:03 UTC, mohamedalichelbi approved these changes

2022-09-26 20:54 UTC, lennczar approved these changes

2022-09-26 20:55 UTC, merged